 DROP TYPE IF EXISTS kitsap_unit_type;  CREATE TYPE kitsap_unit_type AS ENUM ('ADU', 'ALQ', 'APT', 'CONDO', 'DUPLEX', 'FOURPLEX', 'GAR', 'GH', 'GROUP', 'MANUHOME', 'MH', 'MH-LOT', 'MH-PARK', 'MH-SC', 'MH-TEMP', 'OPEN', 'OPENSPACE', 'PARKING', 'RETAIL', 'SFR', 'SLIP', 'SUITE', 'TRIPLEX', 'UNKNOWN', 'UTIL_CELL', 'UTIL_OTHER', 'UTIL_PUMP', 'UTIL_VAULT', 'UTIL_WELL', 'VACANT');

